# User Configuration (Auto-generated)
# Overrides settings.py

PLAYER_NAME = 'DanieleM'
HP_MAX = 120
HP_CURRENT = 100
AP_MAX = 90
AP_CURRENT = 90
LEVEL = 28
RADIATION_VALUE = -40
RADIATION_FLUCTUATION = 'Static'
PIP_BOY_LIGHT = (5, 255, 0)
PIP_BOY_MID = (0, 127, 0)
PIP_BOY_DARK = (0, 63, 0)
PIP_BOY_DARKER = (0, 63, 0)
SCREEN_WIDTH = 320
SCREEN_HEIGHT = 255
FPS = 24
SOUND_ON = True
SHOW_CRT = True
BLOOM_EFFECT = True
REAL_MAP = True
FM_RADIO = False
FAKE_LOCATION = 'Mojave'
UI_STYLE = 'Fallout_NV'
SHOW_ALL_MARKERS = True
DATE_MODE = 'Real'
